// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using examenDos.DataBase;

#nullable disable

namespace examenDos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240727013441_segundamigracion")]
    partial class segundamigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("examenDos.DataBase.Entities.CustomersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("CommissionRate")
                        .HasMaxLength(100)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("commissionRate");

                    b.Property<DateTime>("DisbursemenDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("disbursementDate");

                    b.Property<DateTime>("FirstPayment")
                        .HasColumnType("datetime2")
                        .HasColumnName("firstPaymentDate");

                    b.Property<int>("InteresRate")
                        .HasColumnType("int")
                        .HasColumnName("interesRate");

                    b.Property<int>("Term")
                        .HasColumnType("int")
                        .HasColumnName("term");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("customers", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
